[package]
name = "getshells_multi"
version = "0.1.0"
edition = "2021"


[profile.release]
opt-level = 3
lto = true
panic = "abort"

[dependencies]
ahash = { version = "0.8.3", features = ["no-rng"] }
